#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

# Install HAProxy
sudo apt-get install -y haproxy

# Enable management via the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAProxy
cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 320432-web-01 52.207.56.49:80 check
    server 320432-web-02 54.173.66.120:80 check
EOT

# Restart HAProxy to apply changes
sudo service haproxy restart

