#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables
hour=0

# Using a while loop to display the time
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    minute=1
    while [ $minute -le 59 ]; do
        echo $minute
        ((minute++))
    done

    ((hour++))
done

