#!/usr/bin/env bash
# This script configures an Ubuntu server to update the IP addresses of localhost and facebook.com.

# Update localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Update facebook.com to resolve to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/' /etc/hosts

